-d C:\Users\Andrew Dudaronek\Desktop\UVC_Module_LED\impl\gwsynthesis\UVC_Module_LED.vg
-p GW1N-9C-QFN48-6
-pn GW1N-LV9QN48C6/I5
-cst C:\Users\Andrew Dudaronek\Desktop\UVC_Module_LED\src\constraint.cst
-cfg C:\Users\Andrew Dudaronek\Desktop\UVC_Module_LED\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
